/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 125
#define YY_END_OF_BUFFER 126
static yyconst short int yy_acclist[412] =
    {   0,
      126,  124,  125,  123,  124,  125,  123,  125,  102,  124,
      125,  124,  125,  107,  124,  125,  108,  124,  125,   98,
      124,  125,  103,  124,  125,  124,  125,  114,  124,  125,
      115,  124,  125,   96,  124,  125,   94,  124,  125,  111,
      124,  125,   95,  124,  125,  110,  124,  125,   97,  124,
      125,   68,  124,  125,  113,  124,  125,  112,  124,  125,
      100,  124,  125,   99,  124,  125,  101,  124,  125,  109,
      124,  125,  106,  124,  125,  120,  124,  125,  120,  124,
      125,  120,  124,  125,  120,  124,  125,  120,  124,  125,
      118,  124,  125,  119,  124,  125,  105,  124,  125,  120,

      124,  125,  120,  124,  125,  120,  124,  125,  120,  124,
      125,  120,  124,  125,  120,  124,  125,  120,  124,  125,
      120,  124,  125,  120,  124,  125,  120,  124,  125,  120,
      124,  125,  120,  124,  125,  120,  124,  125,  120,  124,
      125,  120,  124,  125,  116,  124,  125,  104,  124,  125,
      117,  124,  125,  123,   76,   70,   83,   73,   84,   81,
       79,   80,   92,   89,  122,   82,   68,   93,   87,   77,
       75,   91,   78,   88,  120,  120,  120,  120,  120,  120,
       86,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,    1,  120,  120,  120,  120,

      120,   36,  120,    4,  120,  120,   35,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,   41,  120,  120,  120,  120,   85,   74,
       69,   90,  122,   67,   57,   62,   71,   72,  120,  120,
      120,  120,   52,  120,  120,  120,  120,  120,  120,  120,
      120,   33,  120,  120,  120,  120,   46,  120,   47,  120,
      120,    8,  120,  120,   37,  120,   38,  120,   39,  120,
      120,    2,  120,  120,  120,   17,  120,  120,    3,  120,
       15,  120,   32,  120,  120,  120,  120,   50,  120,  120,
      120,  120,  120,  120,   42,  120,   43,  120,   44,  120,

      120,   16,  120,  120,  120,  121,   58,   59,   60,   63,
       64,   65,  120,  120,   28,  120,  120,  120,  120,   48,
      120,  120,   49,  120,  120,  120,  120,    5,  120,   12,
      120,  120,  120,   40,  120,   13,  120,    6,  120,  120,
       31,  120,  120,   27,  120,  120,  120,  120,  120,   55,
      120,   18,  120,   45,  120,  120,  120,  120,   61,   66,
      120,  120,  120,   29,  120,   30,  120,   21,  120,   19,
      120,  120,   25,  120,  120,   56,  120,   10,  120,  120,
      120,  120,   26,  120,   14,  120,  120,   34,  120,    7,
      120,   53,  120,   54,  120,   51,  120,  120,   24,  120,

        9,  120,   20,  120,   11,  120,   23,  120,  120,   22,
      120
    } ;

static yyconst short int yy_accept[278] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   12,   14,   17,
       20,   23,   26,   28,   31,   34,   37,   40,   43,   46,
       49,   52,   55,   58,   61,   64,   67,   70,   73,   76,
       79,   82,   85,   88,   91,   94,   97,  100,  103,  106,
      109,  112,  115,  118,  121,  124,  127,  130,  133,  136,
      139,  142,  145,  148,  151,  154,  155,  156,  156,  157,
      157,  158,  159,  160,  160,  160,  161,  162,  163,  164,
      165,  165,  166,  167,  167,  168,  168,  168,  169,  170,
      171,  172,  173,  174,  175,  176,  177,  178,  179,  180,
      181,  182,  183,  184,  185,  186,  187,  188,  189,  190,

      191,  192,  193,  194,  195,  196,  198,  199,  200,  201,
      202,  204,  206,  207,  209,  210,  211,  212,  213,  214,
      215,  216,  217,  218,  219,  220,  221,  222,  223,  224,
      226,  227,  228,  229,  230,  231,  232,  233,  233,  233,
      234,  235,  235,  235,  235,  236,  236,  236,  236,  237,
      238,  239,  240,  241,  242,  243,  245,  246,  247,  248,
      249,  250,  251,  252,  254,  255,  256,  257,  259,  261,
      262,  264,  265,  267,  269,  271,  272,  274,  275,  276,
      278,  279,  281,  283,  285,  286,  287,  288,  290,  291,
      292,  293,  294,  295,  297,  299,  301,  302,  304,  305,

      306,  307,  307,  308,  309,  310,  310,  311,  312,  313,
      314,  315,  317,  318,  319,  320,  322,  323,  325,  326,
      327,  328,  330,  332,  333,  334,  336,  338,  340,  341,
      343,  344,  346,  347,  348,  349,  350,  352,  354,  356,
      357,  358,  359,  360,  361,  362,  363,  364,  366,  368,
      370,  372,  373,  375,  376,  378,  380,  381,  382,  383,
      385,  387,  388,  390,  392,  394,  396,  398,  399,  401,
      403,  405,  407,  409,  410,  412,  412
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   19,   24,   19,   25,   19,   26,   27,   28,
       29,   30,   31,   32,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   34,   33,
       33,   35,   36,   33,   33,   37,   33,   33,   33,   33,
       38,   39,   40,   41,   33,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   33,   51,   52,   53,   54,
       55,   56,   33,   57,   58,   59,   60,   61,   62,   63,
       64,   33,   65,   66,   67,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[68] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    4,    4,
        4,    4,    4,    4,    4,    1,    1,    1,    1,    1,
        1,    1,    4,    4,    4,    4,    4,    1,    1,    1,
        1,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    1,    1,    1
    } ;

static yyconst short int yy_base[282] =
    {   0,
        0,    0,  335,  336,   66,   68,  305,   67,  336,  336,
      304,   64,  293,  336,  336,  302,  301,  336,   45,  312,
       63,   63,  302,  336,   49,   60,   65,  336,  336,    0,
      271,  280,   45,  279,  336,  336,  295,   38,   42,   52,
      259,   51,   86,   95,   56,   70,  262,  275,   72,   65,
      113,  271,  336,   50,  336,  124,  336,  116,  336,    0,
      336,  336,  336,  309,  308,  336,  336,  336,  336,  300,
      303,    0,  336,  137,  153,  144,  159,  336,  286,  336,
      336,  336,  336,  285,    0,  254,  254,  259,  253,  265,
      336,  244,  265,  251,  259,  262,  249,  260,  247,  242,

      239,  239,  276,  273,  243,    0,  237,  115,  272,  269,
        0,    0,  235,    0,  231,  234,  229,   89,  228,  243,
      104,  233,  123,  228,  140,  227,  122,  261,  258,    0,
      222,  233,  139,  336,  336,  336,  336,  265,  134,    0,
      171,  177,  256,  253,  336,  178,  254,  251,  336,  336,
      336,  223,  212,  224,  220,    0,  215,  218,  215,  224,
      208,   86,  205,    0,  217,  209,  215,    0,    0,  202,
        0,  234,    0,    0,    0,  206,    0,  201,  212,    0,
      209,    0,    0,    0,  194,  206,  193,  191,  204,  199,
      202,  201,  221,    0,    0,    0,  203,    0,  187,  191,

      336,  217,  336,  336,  336,  216,  336,  336,  336,  185,
      187,    0,  184,  193,  177,    0,  184,    0,  175,  183,
      186,    0,    0,  174,  184,    0,    0,    0,  178,    0,
      163,    0,  169,  171,  155,  152,    0,    0,    0,  163,
      163,  162,  336,  336,  153,  147,  157,    0,    0,    0,
        0,  150,    0,  143,    0,    0,  134,  143,  127,    0,
        0,  108,    0,    0,    0,    0,    0,   93,    0,    0,
        0,    0,    0,   78,    0,  336,  213,  217,   94,  221,
      225
    } ;

static yyconst short int yy_def[282] =
    {   0,
      276,    1,  276,  276,  276,  276,  276,  277,  276,  276,
      276,  276,  278,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  279,
      279,  279,  279,  279,  276,  276,  276,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  276,  276,  276,  276,  276,  277,  276,  277,
      276,  276,  276,  276,  278,  276,  276,  276,  276,  276,
      280,  281,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  279,  279,  279,  279,  279,  279,
      276,  279,  279,  279,  279,  279,  279,  279,  279,  279,

      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  276,  276,  276,  276,  280,  280,  281,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,

      276,  276,  276,  276,  276,  276,  276,  276,  276,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  276,  276,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,    0,  276,  276,  276,  276,
      276
    } ;

static yyconst short int yy_nxt[404] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       22,   22,   22,   22,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,    4,   36,
       37,   38,   39,   40,   41,   42,   43,   30,   30,   44,
       30,   45,   46,   30,   30,   47,   48,   49,   50,   51,
       30,   52,   30,   30,   53,   54,   55,   56,   56,   56,
       56,   59,   62,   68,   69,   71,   79,   80,  134,   74,
       72,   75,   75,   75,   75,   75,   75,   75,   81,   82,
       88,   73,   63,   83,   84,   92,   94,   85,   95,   93,

       96,  115,  100,   89,  101,   60,   97,  103,   98,  104,
      116,  117,   76,  102,  108,  135,  109,  122,  110,  111,
       59,  125,   77,  275,  118,   56,   56,  105,  126,  119,
      123,  124,  127,  180,  128,  172,  129,  130,  173,  106,
      107,  112,  193,  219,  220,  194,  139,  113,  114,  181,
      184,  201,  274,  273,   60,  141,  141,  141,  141,  141,
      141,  141,  185,  142,  187,  143,  131,  144,  145,   74,
      132,   75,   75,   75,   75,   75,   75,   75,  146,  188,
      147,  190,  148,  149,  199,  272,  271,  270,  200,  141,
      141,  141,  141,  141,  141,  141,  269,  202,  206,  191,

      203,  207,   76,  268,  267,  266,  265,  264,  263,  262,
      261,  260,   77,   58,  259,   58,   58,   64,  258,  257,
       64,  138,  138,  138,  138,  140,  256,  140,  140,  255,
      254,  253,  252,  251,  250,  249,  248,  247,  246,  245,
      244,  243,  242,  241,  240,  239,  238,  237,  236,  235,
      234,  233,  232,  231,  230,  229,  228,  227,  226,  225,
      224,  223,  222,  221,  218,  217,  216,  215,  214,  213,
      212,  211,  210,  209,  208,  205,  204,  139,  198,  197,
      196,  195,  192,  189,  186,  183,  182,  179,  178,  177,
      176,  175,  174,  171,  170,  169,  168,  167,  166,  165,

      164,  163,  162,  161,  160,  159,  158,  157,  156,  155,
      154,  153,  152,  151,  150,  139,  137,   64,  136,  133,
      121,  120,   99,   91,   90,   87,   86,   78,   70,   67,
       66,   65,   61,   57,  276,    3,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,

      276,  276,  276
    } ;

static yyconst short int yy_chk[404] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    5,    6,
        6,    8,   12,   19,   19,   21,   25,   25,   54,   22,
       21,   22,   22,   22,   22,   22,   22,   22,   26,   26,
       33,   21,   12,   27,   27,   38,   39,  279,   39,   38,

       40,   45,   42,   33,   42,    8,   40,   43,   40,   43,
       45,   46,   22,   42,   44,   54,   44,   49,   44,   44,
       58,   50,   22,  274,   46,   56,   56,   43,   50,   46,
       49,   49,   51,  118,   51,  108,   51,   51,  108,   43,
       43,   44,  127,  162,  162,  127,  139,   44,   44,  118,
      121,  139,  268,  262,   58,   74,   74,   74,   74,   74,
       74,   74,  121,   76,  123,   76,   51,   76,   76,   75,
       51,   75,   75,   75,   75,   75,   75,   75,   77,  123,
       77,  125,   77,   77,  133,  259,  258,  257,  133,  141,
      141,  141,  141,  141,  141,  141,  254,  142,  146,  125,

      142,  146,   75,  252,  247,  246,  245,  242,  241,  240,
      236,  235,   75,  277,  234,  277,  277,  278,  233,  231,
      278,  280,  280,  280,  280,  281,  229,  281,  281,  225,
      224,  221,  220,  219,  217,  215,  214,  213,  211,  210,
      206,  202,  200,  199,  197,  193,  192,  191,  190,  189,
      188,  187,  186,  185,  181,  179,  178,  176,  172,  170,
      167,  166,  165,  163,  161,  160,  159,  158,  157,  155,
      154,  153,  152,  148,  147,  144,  143,  138,  132,  131,
      129,  128,  126,  124,  122,  120,  119,  117,  116,  115,
      113,  110,  109,  107,  105,  104,  103,  102,  101,  100,

       99,   98,   97,   96,   95,   94,   93,   92,   90,   89,
       88,   87,   86,   84,   79,   71,   70,   65,   64,   52,
       48,   47,   41,   37,   34,   32,   31,   23,   20,   17,
       16,   13,   11,    7,    3,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,

      276,  276,  276
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 ".\\rust_lexer.l"
#define INITIAL 0
#line 2 ".\\rust_lexer.l"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <dirent.h>  


/* Función auxiliar para imprimir en formato tabla */
void imprimir_token(const char *tipo, const char *lexema) {
    printf("%-20s %s\n", tipo, lexema);
}

#line 618 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 19 ".\\rust_lexer.l"


 /* Palabras clave (cada una en su línea) */
#line 773 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 277 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 336 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 22 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 23 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 24 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 25 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 26 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 27 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 28 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 29 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 30 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 31 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 32 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 33 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 34 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 35 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 36 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 37 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 38 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 39 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 40 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 41 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 42 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 43 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 44 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 45 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 46 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 47 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 48 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 49 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 50 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 51 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 52 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 53 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 54 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 55 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 56 ".\\rust_lexer.l"
{ imprimir_token("KEYWORD", yytext); }
	YY_BREAK
/* Tipos primitivos */
case 36:
YY_RULE_SETUP
#line 59 ".\\rust_lexer.l"
{ imprimir_token("TYPE", yytext); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 60 ".\\rust_lexer.l"
{ imprimir_token("TYPE", yytext); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 61 ".\\rust_lexer.l"
{ imprimir_token("TYPE", yytext); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 62 ".\\rust_lexer.l"
{ imprimir_token("TYPE", yytext); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 63 ".\\rust_lexer.l"
{ imprimir_token("TYPE", yytext); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 64 ".\\rust_lexer.l"
{ imprimir_token("TYPE", yytext); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 65 ".\\rust_lexer.l"
{ imprimir_token("TYPE", yytext); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 66 ".\\rust_lexer.l"
{ imprimir_token("TYPE", yytext); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 67 ".\\rust_lexer.l"
{ imprimir_token("TYPE", yytext); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 68 ".\\rust_lexer.l"
{ imprimir_token("TYPE", yytext); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 69 ".\\rust_lexer.l"
{ imprimir_token("TYPE", yytext); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 70 ".\\rust_lexer.l"
{ imprimir_token("TYPE", yytext); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 71 ".\\rust_lexer.l"
{ imprimir_token("TYPE", yytext); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 72 ".\\rust_lexer.l"
{ imprimir_token("TYPE", yytext); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 73 ".\\rust_lexer.l"
{ imprimir_token("TYPE", yytext); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 74 ".\\rust_lexer.l"
{ imprimir_token("TYPE", yytext); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 75 ".\\rust_lexer.l"
{ imprimir_token("TYPE", yytext); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 76 ".\\rust_lexer.l"
{ imprimir_token("TYPE", yytext); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 77 ".\\rust_lexer.l"
{ imprimir_token("TYPE", yytext); }
	YY_BREAK
/* Literales booleanos */
case 55:
YY_RULE_SETUP
#line 80 ".\\rust_lexer.l"
{ imprimir_token("BOOL", yytext); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 81 ".\\rust_lexer.l"
{ imprimir_token("BOOL", yytext); }
	YY_BREAK
/* Literales con sufijo de tipo */
case 57:
YY_RULE_SETUP
#line 84 ".\\rust_lexer.l"
{ imprimir_token("INT_SUFFIX", yytext); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 85 ".\\rust_lexer.l"
{ imprimir_token("INT_SUFFIX", yytext); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 86 ".\\rust_lexer.l"
{ imprimir_token("INT_SUFFIX", yytext); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 87 ".\\rust_lexer.l"
{ imprimir_token("INT_SUFFIX", yytext); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 88 ".\\rust_lexer.l"
{ imprimir_token("INT_SUFFIX", yytext); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 89 ".\\rust_lexer.l"
{ imprimir_token("INT_SUFFIX", yytext); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 90 ".\\rust_lexer.l"
{ imprimir_token("INT_SUFFIX", yytext); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 91 ".\\rust_lexer.l"
{ imprimir_token("INT_SUFFIX", yytext); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 92 ".\\rust_lexer.l"
{ imprimir_token("INT_SUFFIX", yytext); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 93 ".\\rust_lexer.l"
{ imprimir_token("INT_SUFFIX", yytext); }
	YY_BREAK
/* Números flotantes */
case 67:
YY_RULE_SETUP
#line 96 ".\\rust_lexer.l"
{ imprimir_token("FLOAT", yytext); }
	YY_BREAK
/* Enteros simples */
case 68:
YY_RULE_SETUP
#line 99 ".\\rust_lexer.l"
{ imprimir_token("INT", yytext); }
	YY_BREAK
/* Caracteres */
case 69:
YY_RULE_SETUP
#line 102 ".\\rust_lexer.l"
{ imprimir_token("CHAR", yytext); }
	YY_BREAK
/* Cadenas */
case 70:
YY_RULE_SETUP
#line 105 ".\\rust_lexer.l"
{ imprimir_token("STRING", yytext); }
	YY_BREAK
/* Operadores de varios caracteres */
case 71:
YY_RULE_SETUP
#line 108 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 109 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 110 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 111 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 112 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 113 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 114 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 115 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 116 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 117 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 118 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 119 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 120 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 121 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 122 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 123 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 124 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 125 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 126 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 127 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 128 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 129 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 130 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
/* Operadores de un solo carácter y símbolos */
case 94:
YY_RULE_SETUP
#line 133 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 134 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 135 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 136 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 137 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 138 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 139 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 140 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 141 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 142 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 143 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 144 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 145 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 146 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 147 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 148 ".\\rust_lexer.l"
{ imprimir_token("OP", yytext); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 149 ".\\rust_lexer.l"
{ imprimir_token("DOT", yytext); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 150 ".\\rust_lexer.l"
{ imprimir_token("COMMA", yytext); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 151 ".\\rust_lexer.l"
{ imprimir_token("SEMICOLON", yytext); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 152 ".\\rust_lexer.l"
{ imprimir_token("COLON", yytext); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 153 ".\\rust_lexer.l"
{ imprimir_token("LPAREN", yytext); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 154 ".\\rust_lexer.l"
{ imprimir_token("RPAREN", yytext); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 155 ".\\rust_lexer.l"
{ imprimir_token("LBRACE", yytext); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 156 ".\\rust_lexer.l"
{ imprimir_token("RBRACE", yytext); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 157 ".\\rust_lexer.l"
{ imprimir_token("LBRACKET", yytext); }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 158 ".\\rust_lexer.l"
{ imprimir_token("RBRACKET", yytext); }
	YY_BREAK
/* Identificadores */
case 120:
YY_RULE_SETUP
#line 161 ".\\rust_lexer.l"
{ imprimir_token("IDENTIFIER", yytext); }
	YY_BREAK
/* Comentarios (ignorar) */
case 121:
YY_RULE_SETUP
#line 164 ".\\rust_lexer.l"
{ /* ignorar */ }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 165 ".\\rust_lexer.l"
{ /* ignorar */ }
	YY_BREAK
/* Espacios en blanco */
case 123:
YY_RULE_SETUP
#line 168 ".\\rust_lexer.l"
{ /* ignorar */ }
	YY_BREAK
/* Error */
case 124:
YY_RULE_SETUP
#line 171 ".\\rust_lexer.l"
{ printf("ERROR LEXICO: caracter inesperado '%s' en línea %d\n", yytext, yylineno); }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 173 ".\\rust_lexer.l"
ECHO;
	YY_BREAK
#line 1502 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 277 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 277 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 276);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 173 ".\\rust_lexer.l"


/* Función para procesar un archivo */
void procesar_archivo(const char *ruta) {
    FILE *file = fopen(ruta, "r");
    if (!file) {
        perror("Error al abrir archivo");
        return;
    }
    yyin = file;
    printf("\n--- Procesando: %s ---\n", ruta);
    printf("%-20s %s\n", "TOKEN", "LEXEMA");
    printf("----------------------------------------\n");
    yylex();
    fclose(file);
    printf("----------------------------------------\n\n");
}

/* Listar archivos en carpeta Pruebas/ (usando dirent.h) */
int listar_archivos(const char *carpeta, char *archivos[], int max) {
    DIR *dir;
    struct dirent *entry;
    int count = 0;
    dir = opendir(carpeta);
    if (!dir) {
        printf("No se pudo abrir la carpeta '%s'\n", carpeta);
        return 0;
    }
    while ((entry = readdir(dir)) != NULL) {
        if (entry->d_type == DT_REG) {  /* solo archivos regulares */
            if (count < max) {
                archivos[count] = strdup(entry->d_name);
                count++;
            }
        }
    }
    closedir(dir);
    return count;
}

int main(int argc, char **argv) {
    if (argc > 1) {
        /* Si se pasa argumento, procesar ese archivo directamente */
        procesar_archivo(argv[1]);
        return 0;
    }

    /* Modo interactivo: mostrar menú con archivos en Pruebas/ */
    const char *carpeta = "Pruebas";
    char *archivos[50];  /* máximo 50 archivos */
    int n = listar_archivos(carpeta, archivos, 50);

    if (n == 0) {
        printf("No se encontraron archivos en la carpeta '%s'\n", carpeta);
        return 1;
    }

    while (1) {
        printf("\n=== MENU DE PRUEBAS ===\n");
        for (int i = 0; i < n; i++) {
            printf("%d. %s\n", i+1, archivos[i]);
        }
        printf("0. Salir\n");
        printf("Seleccione una opcion: ");

        int opcion;
        scanf("%d", &opcion);
        if (opcion == 0) break;
        if (opcion < 1 || opcion > n) {
            printf("Opcion invalida.\n");
            continue;
        }

        /* Construir ruta completa */
        char ruta[256];
        snprintf(ruta, sizeof(ruta), "%s/%s", carpeta, archivos[opcion-1]);
        procesar_archivo(ruta);
    }

    /* Liberar memoria de los nombres */
    for (int i = 0; i < n; i++) free(archivos[i]);

    return 0;
}